[과제/01] haram/01
RE-CODER-2022/Object-Oriented-Programing pull request #4
Opened 2022-01-01 09:48 UTC by marahohc

# Pull Request

## 진행 주차

1주차

## 진행 중 구현을 못한 사항

1차 과제는 1차원배열로만 구현했는데 상관없는건가요?

2차 과제는 구현중입니다.

2022-01-01 10:57 UTC, JinSeoHan commented
출력형식이 맞지 않는 것 같습니다. 저희가 올려준 자료와 같이 똑같은 출력형식으로 출력되도록 변경하셔야 할 것 같고 정렬되기 전 랜덤값의 출력이 누락되어있는것으로 확인하였습니다. 정렬된 값을 출력하기 전 정렬되지 않은 값을 출력하도록 변경해주십시오. 1차원 배열을 사용하시든 2차원을 사용하시든 자유이지만 정렬되기 전 랜덤값을 출력하고 정렬된 값을 출력하기 위해서는 2차원 배열을 사용하는 것이 더 편할 수 있을 것 같습니다.
<문제에서 요구하는 출력결과>
![image](https://user-images.githubusercontent.com/87526189/147848949-9d12dea7-a647-41e6-8fef-255b40140c8a.png)
<하람님 출력결과>
![image](https://user-images.githubusercontent.com/87526189/147848969-a99a71e4-eaf5-4ecd-923e-747797629185.png)

2022-01-02 05:56 UTC, kwYoohae requested changes
테스트입니다

2022-01-02 06:13 UTC, JinSeoHan commented on haram/01/01.cpp
> +    int arr[num]={0};
arr[num] 은 cin 으로 받은 num값을 동적으로 값을 할당하여 배열을 생성하기 때문에 잘못된 표현입니다.
동적할당을 하는 것이 목적이라면 int *arr = new int[num];으로 표현해야 정확합니다

2022-01-04 07:37 UTC, JinSeoHan requested changes
01.cpp에서 10을 입력하였을 때 출력되지 않는 오류가 있습니다.
![image](https://user-images.githubusercontent.com/87526189/148024657-ff4867e1-9ba5-4479-861a-eb177e53f67e.png)

2022-01-05 06:33 UTC, JinSeoHan approved these changes

2022-01-05 06:38 UTC, kwYoohae approved these changes

2022-01-05 06:38 UTC, merged