[과제/01] leech1211 /01
RE-CODER-2022/Object-Oriented-Programing pull request #5
Opened 2022-01-01 13:58 UTC by leech1211

# Pull Request

## 진행 주차
1주차

## 진행 중 구현을 못한 사항

2차원 배열 전달, 정렬이 어려웠습니다

2022-01-02 06:21 UTC, JinSeoHan requested changes

2022-01-02 06:21 UTC, JinSeoHan commented on leech1211/01/1stWeek_2/Work5.cpp
> +    int narr[last] = {0,};           //1차원 배열 선언
int narr[last] = {0,};  는 동적으로 배열의 크기를 할당하기 때문에 new를 사용하셔서 수정해야합니다.
https://github.com/RE-CODER-2022/Object-Oriented-Programing/pull/4/files#r777170272 참고하시면 됩니다.

2022-01-04 07:48 UTC, JinSeoHan approved these changes

2022-01-04 11:55 UTC, kwYoohae approved these changes
LGTM👍

2022-01-05 06:39 UTC, merged