1주차 과제 제출
RE-CODER-2022/Object-Oriented-Programing pull request #6
Opened 2022-01-02 15:31 UTC by Bjimin

# Pull Request

## 진행 주차

1주차

## 진행 중 구현을 못한 사항

첫번째 과제의 랜덤 값을 이용자에게 입력받는게 맞는건지 모르겠어서 일단 입력받도록 만들었습니다.

2022-01-03 02:33 UTC, kwYoohae commented
파일경로가 다음처럼 `.github/jimin/01`로 되어있습니다.

현재 `.github` 폴더 안에 과제를 넣은 것 같습니다. 경로 수정해서 다시 commit 진행해주시면 될 것 같습니다. 
![image](https://user-images.githubusercontent.com/74089271/147896154-b20d4309-4d01-4956-b3df-6d14e56ea990.png)

2022-01-04 08:22 UTC, JinSeoHan requested changes
01.cpp 난수 생성하여 구현 부탁드립니다

2022-01-05 06:37 UTC, JinSeoHan approved these changes

2022-01-05 06:40 UTC, kwYoohae approved these changes

2022-01-05 06:40 UTC, merged